import { Agent, Lead } from "@/lib/types";

export type QualificationResult = {
  score: number;
  reason: string;
  emailResponse: string;
};

function fallbackResult(agent: Agent, lead: Omit<Lead, "id" | "agent_id" | "created_at" | "status" | "qualification_score" | "qualification_reason" | "ai_response" | "notes">): QualificationResult {
  const score = lead.timeline.toLowerCase().includes("now") ? 8 : 6;
  return {
    score,
    reason: `Fallback score based on timeline (${lead.timeline}) and submitted profile completeness.`,
    emailResponse: `Hi ${lead.full_name},\n\nThanks for reaching out to ${agent.agency_name}. I can help with ${lead.insurance_type} coverage options in your area. Could you share your current carrier and your target effective date?\n\nYou can also pick a call time here: ${agent.calendar_link ?? "Please reply with a good time and we will confirm."}\n\n- ${agent.name}`
  };
}

export async function qualifyLeadWithClaude(params: {
  agent: Agent;
  lead: Omit<Lead, "id" | "agent_id" | "created_at" | "status" | "qualification_score" | "qualification_reason" | "ai_response" | "notes">;
}): Promise<QualificationResult> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  const { agent, lead } = params;

  if (!apiKey) {
    return fallbackResult(agent, lead);
  }

  const prompt = `You are an insurance lead qualification assistant for ${agent.name} at ${agent.agency_name}.\n\nLead info:\n- Name: ${lead.full_name}\n- Email: ${lead.email}\n- Phone: ${lead.phone}\n- Insurance Type: ${lead.insurance_type}\n- Current Coverage: ${lead.current_coverage}\n- Timeline: ${lead.timeline}\n- ZIP: ${lead.zip_code}\n\nAgent voice preferences: ${agent.brand_voice ?? "Professional, concise, friendly"}\nBooking link: ${agent.calendar_link ?? "No booking link provided"}\n\nReturn STRICT JSON with fields:\n{\n  \"score\": number (1-10),\n  \"reason\": string (max 220 chars),\n  \"emailResponse\": string (max 1200 chars)\n}\n\nThe emailResponse should greet the lead by first name, ask 2-3 smart follow-up questions tailored to the insurance type, and include the booking link.`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: "claude-3-5-sonnet-20241022",
      max_tokens: 700,
      temperature: 0.2,
      messages: [{ role: "user", content: prompt }]
    })
  });

  if (!response.ok) {
    return fallbackResult(agent, lead);
  }

  const data = (await response.json()) as {
    content?: Array<{ type: string; text?: string }>;
  };

  const text = data.content?.find((item) => item.type === "text")?.text?.trim();
  if (!text) {
    return fallbackResult(agent, lead);
  }

  try {
    const parsed = JSON.parse(text) as QualificationResult;
    const score = Math.max(1, Math.min(10, Number(parsed.score) || 5));
    return {
      score,
      reason: parsed.reason?.slice(0, 220) || "Qualification generated by AI.",
      emailResponse: parsed.emailResponse?.slice(0, 1200) || fallbackResult(agent, lead).emailResponse
    };
  } catch {
    return fallbackResult(agent, lead);
  }
}
